name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - feature
  - title: '🐛 Fixes'
    labels:
      - bug
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## Changelog

  $CHANGES

  _This changelog was generated automatically._
